chezmoi: update

diff --git a/dot_bash_utils b/dot_bash_utils
--- a/dot_bash_utils
+++ b/dot_bash_utils
@@ -5,3 +5,24 @@ alias p='git pull origin HEAD'
 alias push='git push origin HEAD'
 export HISTFILESIZE=1000000
 export HISTSIZE=1000000
+function dotfiles {
+	(
+	set -e
+	chezmoi update
+	chezmoi apply
+	cd ~/.local/share/chezmoi/
+	git add -u
+	git diff --cached origin/main
+	git status
+	read -r -p "Commit and push? [y/N] " response
+	case "$response" in
+		y)
+			git commit -m "chezmoi: update"
+			git push
+			;;
+		*)
+			echo "Aborted"
+			;;
+	esac
+	)
+}
