chezmoi: update

diff --git a/dot_bash_utils b/dot_bash_utils
--- a/dot_bash_utils
+++ b/dot_bash_utils
@@ -1,28 +1,54 @@
 # Bash utils by Sina
 # Source this in your ~/.bash_profile
 # vim: ft=bash
-alias p='git pull origin HEAD'
-alias push='git push origin HEAD'
 export HISTFILESIZE=1000000
 export HISTSIZE=1000000
+export EDITOR=nvim
+alias v="${EDITOR} -O"
+alias view="${EDITOR} -R -O"
+alias date-slug='date +%F-%T'
+alias grep='grep --color'
+alias abspath='readlink -f'
+
+alias p='git pull origin HEAD'
+alias push='git push origin HEAD'
+alias gd='git diff --stat -p -w' # -U0
+alias gdc='git diff --stat -p -w --cached' # -U0
+alias gsh='git show --stat -p -w' #  -U0
+alias gs='git status'
+
+# open results of rg in EDITOR
+function vrg() {
+  $EDITOR -O $(rg -l "$@")
+}
+
+function capture () {
+    local out;
+    out="$(mktemp --tmpdir=. --suffix=.txt)";
+    tmux capture-pane -J -S- -b mybuf;
+    tmux save-buffer -b mybuf "${out}";
+    echo "${out}";
+    nvim "${out}"
+}
+
 function dotfiles {
 	(
-	set -e
-	chezmoi update
-	chezmoi apply
-	cd ~/.local/share/chezmoi/
-	git add -u
-	git diff --cached origin/main
-	git status
-	read -r -p "Commit and push? [y/N] " response
-	case "$response" in
-		y)
-			git commit -m "chezmoi: update"
-			git push
-			;;
-		*)
-			echo "Aborted"
-			;;
-	esac
+		set -e
+		chezmoi update
+		chezmoi apply
+		cd ~/.local/share/chezmoi/
+		git add -u
+		git diff --cached origin/main
+		git status
+		read -r -p "Commit and push? [y/N] " response
+		case "$response" in
+			y)
+				git commit -m "chezmoi: update"
+				git push
+				;;
+			*)
+				echo "Aborted"
+				;;
+		esac
 	)
 }
